/* Generated By:JavaCC: Do not edit this line. KeepParserConstants.java */
package rdf.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KeepParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE = 1;
  /** RegularExpression Id. */
  int WORD = 2;
  /** RegularExpression Id. */
  int CHAR = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NEWLINE>",
    "<WORD>",
    "<CHAR>",
  };

}
